insert into courses values(1,'Базовый курс');
insert into courses values(2,'Йога');
insert into courses values(3,'Зумба');
insert into courses values(4,'Боди-балет');
insert into courses values(5,'Аргентинское танго');
insert into courses values(6,'Пилатес');
insert into courses values(7,'Клубная латина');
insert into courses values(8,'Танцевальный маньяк');
insert into courses values(9,'Бальные танцы');


insert into courselevels(id, course_id, name) values(1,1,'Базовый - 1.0');
insert into courselevels(id, course_id, name) values(2,1,'Базовый - 2.0');
insert into courselevels(id, course_id, name) values(3,2,'Йога');
insert into courselevels(id, course_id, name) values(4,3,'Зумба');
insert into courselevels(id, course_id, name) values(5,4,'Боди-балет');
insert into courselevels(id, course_id, name) values(6,5,'Танго');
insert into courselevels(id, course_id, name) values(7,6,'Пилатес');
insert into courselevels(id, course_id, name) values(8,7,'Сальса-начинающие');
insert into courselevels(id, course_id, name) values(9,7,'Сальса-продолжающие');
insert into courselevels(id, course_id, name) values(10,7,'Бачата-начинающие');
insert into courselevels(id, course_id, name) values(11,7,'Бачата-продолжающие');
insert into courselevels(id, course_id, name) values(12,7,'Кизомба-начинающие');
insert into courselevels(id, course_id, name) values(13,7,'Кизомба-продолжающие');
insert into courselevels(id, course_id, name) values(14,8,'Бальные танцы');
insert into courselevels(id, course_id, name) values(15,9,'Базовый - 1.0');
insert into courselevels(id, course_id, name) values(16,9,'Базовый - 2.0');
insert into courselevels(id, course_id, name) values(17,9,'Зумба');
insert into courselevels(id, course_id, name) values(18,9,'Боди-балет');
insert into courselevels(id, course_id, name) values(19,9,'Танго');
insert into courselevels(id, course_id, name) values(20,9,'Пилатес');
insert into courselevels(id, course_id, name) values(21,9,'Сальса-начинающие');
insert into courselevels(id, course_id, name) values(22,9,'Сальса-продолжающие');
insert into courselevels(id, course_id, name) values(23,9,'Бачата-начинающие');
insert into courselevels(id, course_id, name) values(24,9,'Бачата-продолжающие');
insert into courselevels(id, course_id, name) values(25,9,'Кизомба-начинающие');
insert into courselevels(id, course_id, name) values(26,9,'Кизомба-продолжающие');
insert into courselevels(id, course_id, name) values(27,9,'Бальные танцы');
